### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by krrishdholakia** [hupe1980/golc#4]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/hupe1980/golc/blob/97e566d6e4f95ac998e8417c4dd7b73a6de359b8/model/chatmodel/anthropic.go#L41

Would love to know if this might help - https://github.com/BerriAI/litellm

~100 lines of code, that standardizes all the llm api calls to the OpenAI call
```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)
```

**Comment by hupe1980** [comment]
Thanks for the tip, but golc isn't a python project
