### ISSUE TITLE
template: template:5:19: executing "template" at <.query>: map has no entry for key "query"

### ISSUE THREAD

**Issue by jimallen** [hupe1980/golc#5]
Thanks for the project, I'm running across this issue in the [conversational_retrieval_qa_rag](https://github.com/hupe1980/golc/tree/main/examples/conversational_retrieval_qa_rag) example. 

```sh
template: template:5:19: executing "template" at <.query>: map has no entry for key "query"
```

It only happens on the second call though. I'm stumped. 

```go
result2, err := golc.Call(context.Background(), conversationalRetrievalQAChain, schema.ChainValues{
		"question": question2,
	})
```

Thanks again, happy to contribute if you can point me in a direction.

**Comment by hupe1980** [comment]
Thank you for the bug report. There was an error in the prompt template. A fix will be released soon
